//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponsivePortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResponsivePortal.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin error adding config portal details.
        /// </summary>
        public static string AdminAddConfigDetailPortal {
            get {
                return ResourceManager.GetString("AdminAddConfigDetailPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin error adding language.
        /// </summary>
        public static string AdminAddConfigLanguage {
            get {
                return ResourceManager.GetString("AdminAddConfigLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error editing breadcrumb view.
        /// </summary>
        public static string AdminBreadcrumbEditError {
            get {
                return ResourceManager.GetString("AdminBreadcrumbEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin configuration error.
        /// </summary>
        public static string AdminConfigError {
            get {
                return ResourceManager.GetString("AdminConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin get portals error.
        /// </summary>
        public static string AdminGetPortals {
            get {
                return ResourceManager.GetString("AdminGetPortals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting admin user name.
        /// </summary>
        public static string AdminGetUserName {
            get {
                return ResourceManager.GetString("AdminGetUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin login error.
        /// </summary>
        public static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application exception, see log file for details.
        /// </summary>
        public static string ApplicationExceptionError {
            get {
                return ResourceManager.GetString("ApplicationExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTACHMENTS.
        /// </summary>
        public static string Art_Attachments {
            get {
                return ResourceManager.GetString("Art_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTRIBUTES.
        /// </summary>
        public static string Art_Attributes {
            get {
                return ResourceManager.GetString("Art_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string Art_Categories {
            get {
                return ResourceManager.GetString("Art_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was this answer helpful?.
        /// </summary>
        public static string Art_Feedback {
            get {
                return ResourceManager.GetString("Art_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified:.
        /// </summary>
        public static string Art_Modified {
            get {
                return ResourceManager.GetString("Art_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATED ANSWERS.
        /// </summary>
        public static string Art_RelAnswers {
            get {
                return ResourceManager.GetString("Art_RelAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATED LINKS.
        /// </summary>
        public static string Art_RelLinks {
            get {
                return ResourceManager.GetString("Art_RelLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with article content.
        /// </summary>
        public static string ArticleFileContentError {
            get {
                return ResourceManager.GetString("ArticleFileContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting article KB name.
        /// </summary>
        public static string ArticleGetKbName {
            get {
                return ResourceManager.GetString("ArticleGetKbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eror getting article list.
        /// </summary>
        public static string ArticleGetListError {
            get {
                return ResourceManager.GetString("ArticleGetListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting article resource.
        /// </summary>
        public static string ArticleGetResourceError {
            get {
                return ResourceManager.GetString("ArticleGetResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article index page error.
        /// </summary>
        public static string ArticleIndexError {
            get {
                return ResourceManager.GetString("ArticleIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending article email.
        /// </summary>
        public static string ArticleSendEmailError {
            get {
                return ResourceManager.GetString("ArticleSendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting article favorites.
        /// </summary>
        public static string ArticleSetFavError {
            get {
                return ResourceManager.GetString("ArticleSetFavError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting article feedback.
        /// </summary>
        public static string ArticleSetFeedbackError {
            get {
                return ResourceManager.GetString("ArticleSetFeedbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting article rating.
        /// </summary>
        public static string ArticleSetRatingError {
            get {
                return ResourceManager.GetString("ArticleSetRatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating article subscription.
        /// </summary>
        public static string ArticleSubscriptionError {
            get {
                return ResourceManager.GetString("ArticleSubscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse module not found error.
        /// </summary>
        public static string BrowseModuleNotFoundError {
            get {
                return ResourceManager.GetString("BrowseModuleNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing user password.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string clearAll {
            get {
                return ResourceManager.GetString("clearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portal you are accessing is not converted as responsive portal. Please configure the portal using &lt;a href=&apos;/Admin&apos; &gt;Portal Admin &lt;/a&gt;.
        /// </summary>
        public static string ConfigPortalAdminError {
            get {
                return ResourceManager.GetString("ConfigPortalAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENT TYPES.
        /// </summary>
        public static string contentTypes {
            get {
                return ResourceManager.GetString("contentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting CD path.
        /// </summary>
        public static string ConvertCDPathError {
            get {
                return ResourceManager.GetString("ConvertCDPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create view model error.
        /// </summary>
        public static string CreateViewModelError {
            get {
                return ResourceManager.GetString("CreateViewModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean:.
        /// </summary>
        public static string didYouMean {
            get {
                return ResourceManager.GetString("didYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER YOUR RESULTS.
        /// </summary>
        public static string filterYourResults {
            get {
                return ResourceManager.GetString("filterYourResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get solution finder details error.
        /// </summary>
        public static string GetSlnFinderDetailsError {
            get {
                return ResourceManager.GetString("GetSlnFinderDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get view model error.
        /// </summary>
        public static string GetViewModelError {
            get {
                return ResourceManager.GetString("GetViewModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home module not found error.
        /// </summary>
        public static string HomeModuleNotFoundError {
            get {
                return ResourceManager.GetString("HomeModuleNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page error.
        /// </summary>
        public static string HomePageError {
            get {
                return ResourceManager.GetString("HomePageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index error.
        /// </summary>
        public static string IndexError {
            get {
                return ResourceManager.GetString("IndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / output error.
        /// </summary>
        public static string IOError {
            get {
                return ResourceManager.GetString("IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP Address is blocked by this site. Please contact your portal administrator for any assistance..
        /// </summary>
        public static string IPAddressBlockedError {
            get {
                return ResourceManager.GetString("IPAddressBlockedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json error.
        /// </summary>
        public static string JsonError {
            get {
                return ResourceManager.GetString("JsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KNOWLEDGEBASES.
        /// </summary>
        public static string knowledgebases {
            get {
                return ResourceManager.GetString("knowledgebases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging out.
        /// </summary>
        public static string LogOutError {
            get {
                return ResourceManager.GetString("LogOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting user password.
        /// </summary>
        public static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search error.
        /// </summary>
        public static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters Applied.
        /// </summary>
        public static string searchFiltersApplied {
            get {
                return ResourceManager.GetString("searchFiltersApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results for.
        /// </summary>
        public static string searchResultFor {
            get {
                return ResourceManager.GetString("searchResultFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH SUGGESTIONS.
        /// </summary>
        public static string searchSuggestions {
            get {
                return ResourceManager.GetString("searchSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Everything.
        /// </summary>
        public static string SolFinder_SearchEverything {
            get {
                return ResourceManager.GetString("SolFinder_SearchEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Solution Finders.
        /// </summary>
        public static string SolFinder_SearchSolFinders {
            get {
                return ResourceManager.GetString("SolFinder_SearchSolFinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionFinder module not found error.
        /// </summary>
        public static string SolutionFinderModuleNotFoundError {
            get {
                return ResourceManager.GetString("SolutionFinderModuleNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.  Please contact your System Administrator if this persists..
        /// </summary>
        public static string StandardErrorMessage {
            get {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access..
        /// </summary>
        public static string UnAuthorizedAccess {
            get {
                return ResourceManager.GetString("UnAuthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated error.
        /// </summary>
        public static string UserNotAuthedError {
            get {
                return ResourceManager.GetString("UserNotAuthedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
